import News from "@/components/News";
import SideBar from "@/components/SideBar";
import SearchBox from "@/components/news/SearchBox";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-between items-center max-w-6xl mx-auto">
          <div className="hidden sm:inline border-r h-screen">
            <SideBar />
          </div>
          <div>{children}</div>
          <div className="lg:flex-col p-3 h-screen border-l hidden lg:flex w-[24rem]">
            <SearchBox />
            <News />
          </div>
        </div>
      </body>
    </html>
  );
}
